Fix transactions validateAbi requires same list length
stx-labs/stacks.js pull request #1046
Opened 2021-06-25 14:59 UTC by ahsan-javaid

## Description
This PR fixes the issue of transaction with flag validateAbi (true), the validation fails for lists that do not have the same length as the function parameter. This can be reproduced with below snippet:
```
const tx = await makeContractCall({
contractAddress: "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE",
contractName: "send-many-memo",
functionName: "send-many",
functionArgs,
validateWithAbi: true,
senderKey,
network,
}); 
```

For PR closes the issue #981

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] API reference/documentation update
- [ ] Other

## Does this introduce a breaking change?
No

## Are documentation updates required?
No

## Testing information
Steps to test:
- Make a contract call with aforementioned snippet by passing less arguments than function expects.
- makeContractCall will not throw a exception and validation will be passed

## Checklist
- [ ] Code is commented where needed
- [ ] Unit test coverage for new or modified code paths
- [x] `npm run test` passes
- [ ] Changelog is updated
- [ ] Tag 1 of @yknl or @zone117x for review

2021-06-28 16:32 UTC, reedrosenbluth requested changes
@ahsan-javaid I think you may have misunderstood this issue. The issue doesn't concern the length of the list of function args, which should always be equal to what is included in the ABI. Rather, the issue is when a Clarity list is passed as an argument to a function. The ABI validation should accept lists that are less than or equal to the max size specified in the arguments type, but currently the validation is checking for equality.

The line that will need to be changed is here: https://github.com/blockstack/stacks.js/blob/4ce29cb46552721dca446fd1e23e011cd0a5ac52/packages/transactions/src/contract-abi.ts#L331

2021-06-30 19:59 UTC, reedrosenbluth submitted a review, later dismissed
Looks good! Can you include some unit tests in `abi.test.ts` that test for this?

2021-07-02 15:08 UTC, ahsan-javaid commented
> Looks good! Can you include some unit tests in `abi.test.ts` that test for this?

@reedrosenbluth unit tests added.

2021-07-07 13:59 UTC, zone117x approved these changes
LGTM!

2021-07-07 15:39 UTC, ahsan-javaid commented
@zone117x Is this ready for merge. cc: @diwakergupta

2021-07-07 19:07 UTC, diwakergupta approved these changes

2021-07-07 22:02 UTC, kyranjamie approved these changes

2021-07-07 23:52 UTC, merged