Feat/add did resolver package
stx-labs/stacks.js pull request #1053
Opened 2021-07-13 18:40 UTC by Exulansis

## Description

Hi everyone, as part of the following accepted [Stacks grant application](https://github.com/stacksgov/Stacks-Grants/issues/61), Jolocom has defined and  developed a new version of the `did:stack:` DID method, based on the new (smart contract based) iteration of the BNS naming layer. This PR contributes both the new DID Method specification, as well as the implementation of the corresponding DID Resolver module.

### A bit of context

The various development milestones were first outlined in [this document](https://www.notion.so/jolocom/Development-Milestones-ca3cc8622b0c4634be5d41b7200af7e3) (you can notice, contributing the developed code to the [Stacks.JS](https://github.com/blockstack/stacks.js) repository is part of the second milestone).
So far the development of this package has taken place in [this repository](https://github.com/jolocom/Stacks-DID-Resolver) hosted by Jolocom. As the main developments were being wrapped up, the migration process (leading to this PR) has been started.

The following [Github issue](https://github.com/jolocom/stacks-did-resolver/issues/17) on the aforementioned repository summarizes both the undertaken developments and remaining open tasks related to the various milestones.

### What is being contributed?

- A DID Method specification document defining the new iteration / version of the Stacks DID method. Can be found [here](https://github.com/jolocom/stacks.js/blob/feat/add_did_resolver_package/packages/did-resolver/docs/DID_Method_Spec.md). Feedback and suggestions for improvement are of course very welcome!
- A new lerna `package` containing the implementation of the corresponding DID resolver module. The source code, including some documentation  and a set of unit / e2e tests can be found [here](https://github.com/jolocom/stacks.js/tree/feat/add_did_resolver_package/packages/did-resolver).
- A [Universal Resolver](https://github.com/decentralized-identity/universal-resolver) driver for `did:stack:v2` identifiers. The corresponding Docker image can be [found here](https://github.com/jolocom/stacks.js/tree/feat/add_did_resolver_package/packages/did-resolver/uni-resolver-driver). *For context, a similar driver for the previous version of the Blockstack DID method can [be found here](https://github.com/decentralized-identity/uni-resolver-driver-did-stack)*.

The contributed package is self contained, no modifications are required to any other included packages / the build system / project setup.

In case any additional information should be submitted as part of this pull request to simplify / aid the review process, please let me know and I can make the requested changes.

Thank you, and looking forward to the emerging conversation!

2021-07-13 18:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/blockstack/stacks.js?pullRequest=1053) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/blockstack/stacks.js?pullRequest=1053) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/blockstack/stacks.js?pullRequest=1053) it.</sub>

2021-07-14 10:07 UTC, friedger requested changes
Great work!

I have reviewed mainly the documentation, not the code.

I have questions about names owned by multi-sig addresses and contracts.

2021-07-14 10:07 UTC, friedger commented on packages/did-resolver/docs/DID_Method_Spec.md
> +Blockstack is a network for decentralized applications where users own their
"Blockstack" should be replace with "Stacks"

2021-07-14 10:07 UTC, friedger commented on packages/did-resolver/docs/DID_Method_Spec.md
> +The Blockstack DID method is specified as part of its [decentralized naming
Same for "Stacks DID"

2021-07-14 10:07 UTC, friedger commented on packages/did-resolver/docs/DID_Method_Spec.md
> +The version bytes for the various address types are also documented
I am confused about the version code for addresses. Does it matter whether the address of a DID is owned by a multisig wallet? For mainnet, there are now the following version:
*  SP.. (on-chain names and single sig address), 
* SH.. (off-chain names)
* SM.. (multi sig address)
Could you clarify?

2021-07-14 10:07 UTC, friedger commented on packages/did-resolver/README.md
> +This repository includes the implementation for the Stack v2 DID resolver, as well as the corresponding `did:stack:v2` [DID method specification](./docs/DID_Method_Spec.md). As outlined in the specif
Are the blockchain attachments still called "Atlas"?

2021-07-14 10:07 UTC, friedger commented on packages/did-resolver/docs/DID_Method_Spec.md
> +network data and can be retrieved using the Atlas peer network.
Some question for "Atlas"

2021-07-14 10:07 UTC, friedger commented on packages/did-resolver/docs/DID_Method_Spec.md
> +Blockstack supplies a [reference
Stacks supplies..

2021-07-14 10:07 UTC, friedger commented on packages/did-resolver/docs/DID_Method_Spec.md
> +here generates such a TXT record:
That library is deprecated and should not be referenced.

2021-07-14 10:07 UTC, friedger commented on packages/did-resolver/docs/DID_Method_Spec.md
> +# 6. Reference Implementations
This looks dated.

2021-07-14 10:07 UTC, friedger commented on packages/did-resolver/docs/DID_Method_Spec.md
> +# 7. Resources
This as well.

2021-07-14 10:07 UTC, friedger commented on packages/did-resolver/src/constants.ts
> +  test: 'STPJE6KB9CNCVTS9RAFHY1RSXAH381W8RJQV1YCB.BNS-migrated-helper',
That contract does not exist since the reset of the testnet

2021-07-14 10:07 UTC, friedger commented on packages/did-resolver/docs/DID_Method_Spec.md
> +A resolvable Stacks DID can be derived for any on-chain name by concatenating
What about names owned by a contract? Should these names be excluded? Or should the documentation and lib updated to for names owned by contract principals?

2021-07-14 11:18 UTC, Exulansis commented on packages/did-resolver/docs/DID_Method_Spec.md
> +The Blockstack DID method is specified as part of its [decentralized naming
Addressed, as per the comment left above.

2021-07-14 11:21 UTC, Exulansis commented on packages/did-resolver/README.md
> +This repository includes the implementation for the Stack v2 DID resolver, as well as the corresponding `did:stack:v2` [DID method specification](./docs/DID_Method_Spec.md). As outlined in the specif
This is a good question, I would be glad to update all references to Atlas / Gaia / etc. to be consistent across the document. I am not sure what the right formulation would be. I was able to find some sparse documentation on Atlas, but still lack the full picture.

2021-07-14 11:22 UTC, Exulansis commented on packages/did-resolver/docs/DID_Method_Spec.md
> +here generates such a TXT record:
Updated, not marking as resolved yet because I'm pretty sure the python snippit included below will need to be updated as well.

2021-07-14 11:24 UTC, Exulansis commented on packages/did-resolver/docs/DID_Method_Spec.md
> +Blockstack supplies a [reference
Addressed :+1:

2021-07-14 11:27 UTC, Exulansis commented on packages/did-resolver/docs/DID_Method_Spec.md
> +# 6. Reference Implementations
The links in the reference implementation section have been updated now. The exact link for the `HTTP API` endpoint for DID resolution will need to be updated shortly (as the appropriate PR adding the endpoint is opened on the [Stacks Blockchain api repository](https://github.com/blockstack/stacks-blockchain-api)).

2021-07-14 11:34 UTC, Exulansis commented on packages/did-resolver/docs/DID_Method_Spec.md
> +# 6. Reference Implementations
Will update this shortly, are there any other places developers should be pointed towards besides the Discord server (at https://discord.gg/YWa8BmKqvR)

2021-07-14 11:35 UTC, Exulansis commented on packages/did-resolver/docs/DID_Method_Spec.md
> +# 7. Resources
Will update this shortly, are there any other places developers should be pointed towards besides the Discord server (at https://discord.gg/YWa8BmKqvR)

2021-07-14 11:36 UTC, Exulansis commented on packages/did-resolver/src/constants.ts
> +  test: 'STPJE6KB9CNCVTS9RAFHY1RSXAH381W8RJQV1YCB.BNS-migrated-helper',
I just noticed the network was reset. I assume the reset happens regularly, and it makes no sense to reference a specific address for the testnet deployment then, is this correct?

2021-07-15 09:53 UTC, Exulansis commented
I am currently chasing down an issue causing DIDs based on names registered using https://btc.us/ to not resolve correctly. A specific failing example is the following DID:

```
did:stack:v2:SPPJE6KB9CNCVTS9RAFHY1RSXAH381W8RKJDM9J9-0x325f21162b0ef9575de65443121c2102121cd958dfc9426b5ca9ab60e2822125
```

Which was registered in [this transaction](https://explorer.stacks.co/txid/0x325f21162b0ef9575de65443121c2102121cd958dfc9426b5ca9ab60e2822125?chain=mainnet) using https://btc.us/.

The signature verification for the signed profile token, happening as part of [this function](https://github.com/blockstack/stacks.js/blob/master/packages/profile/src/profileTokens.ts#L75), throws [at this point](https://github.com/blockstack/stacks.js/blob/master/packages/profile/src/profileTokens.ts#L113).

The `publicKeyOrAddress` passed in to the function (`SPPJE6KB9CNCVTS9RAFHY1RSXAH381W8RKJDM9J9`) does not match the address [derived here](https://github.com/blockstack/stacks.js/blob/master/packages/profile/src/profileTokens.ts#L106). The public key included in the signed token is:

```
038ae05a9e4fe161244b815494063152b2569417f902300281065eda960780aaad
```
And the resulting derived address is:
```
SP1AZ8G9JW40S83XZPZ0BSZC2289XH9B8SNCAQFR1
```

Which indeed does not match the address encoded in the DID (and displayed in the Stacks Wallet browser extension I used to create the address / sign the transactions to register the BNS name).

I've hit similar issues before during development, and also saw that the relevant code in the `@stacks/profile` repo was updated recently. My issues were mostly related to incorrect version bytes / encoding / using compressed versus uncompressed keys to derive addresses, so this is what I'll test out first. I am currently debugging and will post an update as soon as I get to the bottom of the issue.

In case there are some ideas (it seems like the version bytes are correct / not different, it might be related to compressed / uncompressed pub keys being used to derive the address, but not 100% sure).

2021-07-27 15:12 UTC, agraebe commented
@Exulansis is there a strong reason for this new package being part of the stacks.js monorepo? It would be easier to create a standalone repo and package

2021-07-28 08:24 UTC, Exulansis commented
@agraebe There is no strong reason for the DID resolver to be part of this package, it could easily be made available as a separate repository as well.

I have no strong opinion on this matter, the main goals here are to make it easy for interested developers to install / use the DID resolver module (which has more to do with how it is published to NPM than where the source code lives) as well as to make sure it's easy to maintain / iterate on in the future.

Integrating with this monorepo came up / was suggested during our scoping / sync calls with @jcnelson (alongside the integration with `stacks-blockchain-api`), hence this PR. I assume this decision is not set in stone.

2021-07-28 15:34 UTC, agraebe commented
> @agraebe There is no strong reason for the DID resolver to be part of this package, it could easily be made available as a separate repository as well.
> 
> I have no strong opinion on this matter, the main goals here are to make it easy for interested developers to install / use the DID resolver module (which has more to do with how it is published to NPM than where the source code lives) as well as to make sure it's easy to maintain / iterate on in the future.
> 
> Integrating with this monorepo came up / was suggested during our scoping / sync calls with @jcnelson (alongside the integration with `stacks-blockchain-api`), hence this PR. I assume this decision is not set in stone.

Makes sense! I'd suggest this package should be standalone - stacks.js became an umbrella with already 12 packages and unclear ownership/maintenance. It would make your process more involved too. Maybe it would be possible to tag appropriate folks for review in your own package, so you get some eyes on it but wouldn't be subject to the structure of this monorepo?

2021-07-29 12:22 UTC, friedger commented
The DID Spec doc should go into the docs repo or sips

For the resolver package, I think uses cases like the following should be in stacks.js
```
const did = 'did:stack:v2:SPWA58Z5C5JJW2TTJEM8VZA71NJW2KXXB2HA1V16-d8a9a4528ae833e1894eee676af8d218f8facbf95e166472df2c1a64219b5dfb'

const didDocument = await resolve(did);
```
because the dids are retrieved from the users profile, I guess.

The universal resolver driver is less relevant for stacks.js

2021-08-02 23:11 UTC, agraebe commented
> The DID Spec doc should go into the docs repo or sips
> 
> For the resolver package, I think uses cases like the following should be in stacks.js
> 
> ```
> const did = 'did:stack:v2:SPWA58Z5C5JJW2TTJEM8VZA71NJW2KXXB2HA1V16-d8a9a4528ae833e1894eee676af8d218f8facbf95e166472df2c1a64219b5dfb'
> 
> const didDocument = await resolve(did);
> ```
> 
> because the dids are retrieved from the users profile, I guess.
> 
> The universal resolver driver is less relevant for stacks.js

@Exulansis is this input helpful or would you need more guidance as to what to do inside of stacksjs? Can you take it from here and update the PR (and create new ones in the other repos)?

2021-08-03 10:53 UTC, kyranjamie commented on packages/did-resolver/src/api.ts
> +): FutureInstance<Error, NameInfo> => {
This seems like an unusual API choice to me, have you considered either:

1) **Object argument**. The function takes a single object argument including the network
2) **Currying**. Signature `(network: StacksNetwork) => ({ name, namespace }) => FutureInstance<Error, NameInfo>`

The latter allows reuse of the resulting function without repetition of the network arg.

2021-08-10 17:19 UTC, diwakergupta commented
@Exulansis thanks for this contribution!

> The contributed package is self contained, no modifications are required to any other included packages / the build system / project setup.

Much appreciated 🙏🏽 

Given the following, please feel free to publish the package independently:
- package is self-contained but also non-trivial
- adding a package to stacks.js isn't a one-off thing rather an on-going commitment
- there aren't enough dedicated maintainers in this repo to absorb more packages at this time

We can revisit this at a future date. Meanwhile, adoption and usage of this package would also offer meaningful data points.

For now, I'm going to close out this PR. Thanks again!

2021-08-10 17:19 UTC, closed without merging

2021-08-23 08:00 UTC, Exulansis commented on packages/did-resolver/src/api.ts
> +): FutureInstance<Error, NameInfo> => {
Thank you for the remark, will update this call (and other similar occurrences) to use an object argument. I believe I originally defined these functions to make use of currying, but the partially applied versions of the functions did not end up being too useful given the current structure, so I simplified them but did not change the way the arguments are passed.

2021-08-23 08:06 UTC, Exulansis commented
Thank you for the feedback, @diwakergupta, @agraebe. Apologies for the slow response from my side, I was on a brief holiday (I intended to move this issue forward during it, but ended up spending a lot less time in front of the laptop than I expected).

Now that I am back I will follow up on the suggestions made in this thread, namely:

- Establish a repository, under the Jolocom organization, which hosts the implementation of the DID method (i.e. the codebase contributed in this PR + documentation).
- Publish the stacks DID resolver to NPM, for the time being under the Jolocom namespace.
- Contribute the new DID method specification to the appropriate docs / SIPs repository (would [this](https://github.com/stacksgov/sips) be the right place to open a pull request? Asking because the existing SIPs seem to suggest changes / pertain more to how the Stacks blockchain itself operates, while the DID method spec describes a system built on top of the Stacks chain).

*Besides the SIPs repository, it seems like the DID method spec could also be referenced / linked at some point in [this BNS documentation page](https://docs.stacks.co/build-apps/references/bns#subdomain-registrars), since it currently references DIDs as well.*


I will start opening the corresponding PRs shortly.

Thank you again for the review.

2021-08-23 18:59 UTC, agraebe commented
> Asking because the existing SIPs seem to suggest changes / pertain more to how the Stacks blockchain itself operates, while the DID method spec describes a system built on top of the Stacks chain

I'll let @friedger add this thoughts. Based on my understanding, a PR to the docs would be a good starting point.