Unsigned equivalent of makeContractDeploy
stx-labs/stacks.js pull request #1124
Opened 2021-10-21 11:12 UTC by ahsan-javaid

## Description
This PR introduces `Unsigned equivalent of makeContractDeploy` in the `transaction` package to support the workflow request in #1104
This PR closes the issue #1104

## Type of Change
- [X] New feature
- [ ] Bug fix
- [ ] API reference/documentation update
- [ ] Other

## Does this introduce a breaking change?
No
## Are documentation updates required?
No
## Testing information
1. `npm run test` passed
2. Include the test case to test the `makeUnsignedContractDeploy`

## Checklist
- [X] Code is commented where needed
- [X] Unit test coverage for new or modified code paths
- [X] `npm run test` passes
- [ ] Changelog is updated
- [X] Tag 1 of @yknl or @zone117x for review

2021-10-26 15:12 UTC, reedrosenbluth requested changes
Thanks for this!

There's a lot of duplicate code in this new `makeUnsignedContractDeploy` function. Could you possibly refactor the `makeContractDeploy` function such that it utilized `makeUnsignedContractDeploy` to reduce the amount of duplicate code?

2021-10-27 22:50 UTC, zone117x commented on packages/transactions/src/builders.ts
> +  const unsignedTxOptions = { ...txOptions, publicKey } as UnsignedContractDeployOptions;
It's generally safer to define the object type rather than cast to it, i.e.
```ts
const unsignedTxOptions: UnsignedContractDeployOptions = { ...txOptions, publicKey };
```
Casting allows things like this to pass the typechecker:
```ts
const unsignedTxOptions = { ...txOptions, publicKey, wrong: 124 } as UnsignedContractDeployOptions;
```

2021-10-27 22:51 UTC, zone117x approved these changes
Left a comment around a minor type safety improvement, otherwise LGTM!

2021-10-28 07:19 UTC, ahsan-javaid commented on packages/transactions/src/builders.ts
> +  const unsignedTxOptions = { ...txOptions, publicKey } as UnsignedContractDeployOptions;
Done

2021-11-17 16:27 UTC, kyranjamie approved these changes
Just what I was after, thanks!

2021-11-18 12:43 UTC, kyranjamie commented
@reedrosenbluth can we merge?

2021-11-19 01:44 UTC, merged