Clarity functions typedoc annotations
stx-labs/stacks.js pull request #1273
Opened 2022-05-26 09:56 UTC by ahsan-javaid

## Description
- Add typedoc annotations for clarity functions
- Also add basic examples
- Refer to tests for more details

For details refer to issue #1245

## Type of Change
- [X] New feature
- [ ] Bug fix
- [ ] API reference/documentation update
- [ ] Other

## Does this introduce a breaking change?
No

## Are documentation updates required?
No

## Testing information

Provide context on how tests should be performed.
`npm run test`

## Checklist
- [X] Code is commented where needed
- [ ] Unit test coverage for new or modified code paths
- [X] `npm run test` passes
- [ ] Changelog is updated
- [X] Tag reviewers

2022-06-06 13:51 UTC, janniks requested changes
Looks good! Minor comments,

2022-06-06 13:51 UTC, janniks commented on packages/transactions/src/clarity/types/intCV.ts
> + *  const value = UIntCV('100'); // parameter any of type: number | string | bigint | Uint8Array | BN
Should this be lowercase? Uppercase is the type, right?

2022-06-06 13:51 UTC, janniks commented on packages/transactions/src/clarity/types/responseCV.ts
> + *  const respOKCV = responseErrorCV(intCV(1));
ok !== error

2022-06-07 05:56 UTC, ahsan-javaid commented on packages/transactions/src/clarity/types/intCV.ts
> + *  const value = UIntCV('100'); // parameter any of type: number | string | bigint | Uint8Array | BN
Done!

2022-06-07 05:56 UTC, ahsan-javaid commented on packages/transactions/src/clarity/types/responseCV.ts
> + *  const respOKCV = responseErrorCV(intCV(1));
Done!

2022-06-07 11:38 UTC, merged