draft: clarity value parser
stx-labs/stacks.js pull request #1681
Opened 2024-04-24 11:27 UTC by janniks

2024-05-06 10:27 UTC, hugocaillard commented on packages/transactions/src/clarity/prettyPrint.ts
> +export function stringify(cv: ClarityValue, space = 0): string {
💯

2024-05-06 10:47 UTC, hugocaillard requested changes
I tried it and found this use case that throws a parse error:
```clarity
{ a: 0x68656c6c6f21 }
```

2024-05-06 10:47 UTC, hugocaillard commented on packages/transactions/src/clarity/parser.ts
> +  // todo: add `(tuple` syntax
This todo can be removed

2024-05-06 11:07 UTC, janniks commented
> I tried it and found this use case that throws a parse error:
> 
> ```clar
> { a: 0x68656c6c6f21 }
> ```

@hugocaillard  Good catch, noticed that nested values will be tricky with overlaps. I thought the `entire` combinator solved this, but that's not used for the nested values.. 🙃 -- updated the order to fix this case, there might be more though..

In this case it was detecting the `0x..` as `0` matches an int, and will continue instead of trying other cl-values.

2024-05-13 09:04 UTC, hugocaillard approved these changes
LGTM 🚀

2024-06-17 13:33 UTC, merged