Fixed issue #271
stx-labs/stacks.js pull request #273
Opened 2017-10-22 22:00 UTC by TheSamSmith

Fix for issue #271 so that identityAddress can be accessed in the userData object as part of Hacktoberfest

2017-10-22 22:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/blockstack/blockstack.js?pullRequest=273) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/blockstack/blockstack.js?pullRequest=273) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/blockstack/blockstack.js?pullRequest=273) it.</sub>

2017-10-22 22:05 UTC, TheSamSmith commented
Its not letting me sign the CLA?

2017-10-23 19:46 UTC, TheSamSmith commented
@larrysalibra should be good to merge now

2017-10-23 20:53 UTC, jackzampolin commented
Looks like you are good on the CLA! The bot just needed a good kick.

2018-01-12 09:59 UTC, larrysalibra requested changes

2018-01-12 09:59 UTC, larrysalibra commented on src/auth/authApp.js
> +          identityAddress: tokenPayload.iss,
`tokenPayload.iss` isn't the identity address - it is the decentralized identifier. The identity address needs to be parsed from that.

2018-01-17 21:20 UTC, vsund commented on src/auth/authApp.js
> +          identityAddress: tokenPayload.iss,
I guess this should be only a call to [`getAddressFromDID(did)`](https://github.com/blockstack/blockstack.js/blob/develop/src/dids.js#L25) around `tokenPayload.iss`, correct @larrysalibra?

2018-04-03 12:14 UTC, larrysalibra commented
This was resolved by @bitsphr in https://github.com/blockstack/blockstack.js/pull/391#issuecomment-378228337

Thanks @TheSamSmith for getting the ball rolling on this!

2018-04-03 12:14 UTC, closed without merging