Direct gaia hub storage operations
stx-labs/stacks.js pull request #314
Opened 2017-12-13 17:57 UTC by kantai

This PR implements:

#309 Pass gaia hub root url as part of generating an authentication response
#310 Move gaia hub bearer token generation code from browser into blockstack.js  
#311 Implement direct-to-hub gaia hub storage client

In general, the way it works, is:

1. it bumps the version on the Auth Request
2. tries to read the hubURL from the Auth Response. if it cannot, it defaults to `hub.blockstack.org`
3. stores a user's hubConfig to localStorage

This PR includes a _new_ interface as well, that people may want to advise on. Now that we have a bumped version for the auth request, we need to actually do semantic version checks on those requests. To do this, I added a `isLaterVersion` function to `src/utils.js`

Testing this doesn't require an updated browser (if you use an old browser, the sign in process in the browser will still do the datastore setup and core session token generation even though the app won't use either)

Improvements this should give us:
1. Faster and more reliable writes/reads (and the errors should be more understandable)
2. URLs which match files (i.e., if you putFile(todos.json), the stored file is a `gaia.blockstack.org/hub/<app-addr>/todos.json`
3. Ability to serve applications which use storage over HTTPS (no longer making requests to localhost means no longer having mixed-content errors).

Once the blockstack-browser updates are live, we'll also be able to use storage from the next Windows native build and webapp builds.

2017-12-13 21:52 UTC, jackzampolin commented
fixes https://github.com/blockstack/blockstack-browser/issues/631

2017-12-14 14:43 UTC, larrysalibra commented
@kantai this appears to work for me on locally on todos. And it's much faster! Awesome work!

What do the errors about not being able to decrypt the `appPrivateKey` mean?

(I'm using a browser that hasn't been upgraded)

<img width="1000" alt="screen shot 2017-12-14 at 10 39 24 pm" src="https://user-images.githubusercontent.com/597182/33997661-13a7fbe0-e120-11e7-9f68-6413a9288fbc.png">

2017-12-14 15:02 UTC, kantai commented
`appPrivateKey` errors occur because on the browser authRequest version check (https://github.com/blockstack/blockstack-browser/blob/master/app/js/auth/components/AuthModal.js#L220), version is checked with `===`, not a semantic version check, so the AuthResponse doesn't try to encrypt the appPrivateKey, which leads to those two 'failed decryption' messages.

That's being fixed in the browser branch I'm working on -- https://github.com/blockstack/blockstack-browser/tree/feature/direct-gaia-app-support -- it uses `isLaterVersion` from `blockstack.js` to perform the check

2017-12-14 16:08 UTC, larrysalibra commented
> version is checked with ===, not a semantic version check, so the AuthResponse doesn't try to encrypt the appPrivateKey, which leads to those two 'failed decryption' messages.
Does this mean if app devs update blockstack.js and users keep using an older version of the browser, their app private key will be potentially exposed (eg. in referrer headers)?

2017-12-14 16:22 UTC, kantai commented
> Does this mean if app devs update blockstack.js and users keep using an older version of the browser, their app private key will be potentially exposed (eg. in referrer headers)?

Yes -- 

As alternative to this is to hold off on updating the version of the authRequest message and instead add a field (which would be a non-breaking change) that would allow a new browser version (next release 0.21.5) to determine that the app is capable of communicating with gaia hubs directly without performing a version check. We would also update the version check in browser to perform a release semantic versioning check. Then in future releases, we'd be able to use better version checks.

2017-12-14 23:30 UTC, larrysalibra commented
> As alternative to this is to hold off on updating the version of the authRequest message and instead add a field (which would be a non-breaking change) that would allow a new browser version (next release 0.21.5) to determine that the app is capable of communicating with gaia hubs directly without performing a version check.

I think this approach makes sense. We don't want to leave users in a position where they're exposing private keys.

2017-12-14 23:43 UTC, larrysalibra requested changes
@kantai this works really great for me especially with the fixes you pushed.

A question: can we remove blockstack-storage as a dependency with this pull request?

My two concerns are:

1. That we're potentially leaking unencrypted private keys of users who use the current browser when an app upgrades to this. (previously discussed in an earlier comment)

2. This doesn't have any test coverage. (unless i'm missing it)

Do you think we can make changes to address both of these and still support our time frame?

2017-12-14 23:48 UTC, kantai commented
@larrysalibra 

Yes -- both of these can be addressed pretty quickly. I'll add the test cases and the authRequest changes tomorrow.

2017-12-15 06:10 UTC, brandonparee commented
While testing this PR I noticed that if a user was previously logged into an application they would need to log out and back into the application in order to properly set `hubUrl` in `userData`. 

To work around this I've put in a PR (#317) that will make sure that `hubUrl` is set before calling `connectToGaiaHub`.

2017-12-15 19:22 UTC, kantai commented
Changes in the current version:

1. Unit tests for the gaia hub management functions (the higher level functions aren't tested in the unit cases, as they read config settings from local storage) 
2. 404s (file doesn't exist) returns `null` rather than raising exception
3. Version un-bumped -- now old versions of the blockstack browser will continue to encrypt the app private key
4. Incorporates @brandonparee's PR

2017-12-16 10:25 UTC, merged

2017-12-16 10:26 UTC, larrysalibra reviewed
Looks great! Thanks!