Redirect iOS Auth Requests to HTTPS Browser
stx-labs/stacks.js pull request #502
Opened 2018-07-26 14:03 UTC by wbobeirne

Closes #481. Redirects iOS devices to `https://browser.blockstack.org/...` instead of `blockstack://...`. Tested on iOS simulator to make sure it works, and macOS Safari to make sure it didn't change that behavior.

2018-07-26 14:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/blockstack/blockstack.js?pullRequest=502) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/blockstack/blockstack.js?pullRequest=502) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/blockstack/blockstack.js?pullRequest=502) it.</sub>

2018-07-27 10:24 UTC, larrysalibra requested changes
@wbobeirne this looks good to me except for the failing test that appears to be only because of some lint.

I know we don't have great test coverage at the moment - in the interests of eventually having great test coverage, I'd like to see test coverage on this behavior change.

2018-07-30 15:43 UTC, wbobeirne commented
I feel that this particular function is inherently untestable due to its reliance on `custom-protocol-detection-blockstack`, which is a module that relies _heavily_ on browser APIs, e.g. creating iframes, adding them to the document etc. Perhaps we could do some headless browser testing, but I don't think we have a precedent set for that.

I've fixed the lint issue, let me know what you think would be best for testing.

2018-07-30 20:02 UTC, hstove commented
Yes, agreed that testing this particular function is tricky. In my opinion, this seems like such a small but important change that we can get by with manual testing and QA for now on this, and then merge, so we can get it to developers as soon as possible. Just my 2 cents.

2018-07-31 19:27 UTC, larrysalibra approved these changes
Thanks for the lint fixes @wbobeirne! I think your comments re testing make sense for this.

2018-07-31 19:27 UTC, merged