Feature/tx magic variable
stx-labs/stacks.js pull request #559
Opened 2018-10-30 21:45 UTC by jcnelson

This PR adds `network.getMagicBytes()` and `network.setMagicBytes()`, which lets the user override the magic bytes used to identify Blockstack transactions.  The purpose of this pull request is to enable the user to interact with one or more Blockstack testnets, realized as alternative virtualchains on top of Bitcoin mainnet.  This lets us test other pieces of Blockstack software against Bitcoin mainnet without having to either deal with either interacting with the (highly-prone-to-reorg) Bitcoin testnet or having to run a Bitcoin regtest node.  In particular, when used in conjunction with Blockstack Core and the CLI, this lets us instantiate an alternative Blockstack network so we can test hardware wallets with fake Stacks (but real Bitcoin).

2018-11-01 19:37 UTC, kantai commented on src/network.js
> +  getMagicBytes(): string {
We don't really use getters/setters elsewhere in this object -- so I think it'd be preferable to just use the MAGIC_BYTES field directly.

2018-11-01 19:40 UTC, kantai requested changes
This all looks great to me, and worked when I tried it -- the only change I'd recommend is getting rid of the getter/setter for MAGIC_BYTES. We don't really use them elsewhere in `blockstack.js`, and it'd be good to have a uniformity.

2018-11-01 19:41 UTC, kantai commented
For those looking to also test via `blockstack.js` directly. This is what I did:

```javascript
var bsk = require('.')
var bigi = require('bigi')


bsk.config.network.MAGIC_BYTES = 'di'
// this URL might be different for you...
bsk.config.network.blockstackAPIUrl = 'http://172.17.0.2:16268'

var sk = bsk.makeECPrivateKey()

var sender = bsk.publicKeyToAddress(bsk.getPublicKeyFromPrivate(sk))

// add sender to your testnet genesis block.
//  also, send BTC to it (to fund TX fee)

var recipientSK = bsk.makeECPrivateKey()

var recipient = bsk.publicKeyToAddress(bsk.getPublicKeyFromPrivate(recipientSK))


bsk.transactions.makeTokenTransfer(recipient, 'STACKS', bigi.valueOf(1000), 'TEST!' , sk + '01')
.then(console.log)

// You should see a TX! Broadcast it and wait until your node processes it.
```

2018-11-01 20:47 UTC, kantai commented
Woot!

```
$ docker logs kind_clarke | grep ACCEPT
[2018-11-01 20:35:15,356] [DEBUG] [namedb:483] (7.140604945065792) ACCEPT TOKEN_TRANSFER at (548345, 780) data: address='17zg4aXiDA4ptBEXAAfHJnDqVqEjGLE6Rw', block_id='548345', consensus_hash='0efa29f955c6ae3bb5037039d89dba5e', op='$', recipient='76a914cfd25e09f2d33e1aec73bfcc5b608ec513bbe6c088ac', recipient_address='1KwrtHhRM3GHgeTQFcabbZ43aZc7judLUY', scratch_area='5445535421', sender='76a9144cb912533a6935880df7647fd5232e40aca07b8088ac', token_fee='1000', token_units='STACKS', txid='13bb0fdc939b85b4476f065dcac28abb6ce1f395f03243e1e23dd79904db6c8a', vtxindex='780'
```

2018-11-01 21:16 UTC, jcnelson commented
Thanks for testing @kantai!  I made your requested change.

2018-11-01 22:29 UTC, kantai approved these changes

2018-11-05 05:45 UTC, jcnelson commented
Let me know if I can merge it?  Still waiting for @larrysalibra

2018-11-07 05:51 UTC, yknl commented
Any chance we can get this merged in soon for the wallet release?

2018-11-07 12:08 UTC, larrysalibra reviewed
Apologies for the delay in getting to this.

The looks good to me from reading the code. It's pretty clear what it does and how it does it.

I started going down the rabbit hole of testing this against https://testnet.blockstack.org, but had trouble generating an appropriate stacks address that the faucet would accept.

I modified these lines of @kantai 's test script to use the normal magic bytes and the appropriate api url:

```JavaScript
bsk.config.network.MAGIC_BYTES = 'id'
// this URL might be different for you...
bsk.config.network.blockstackAPIUrl = 'http://testnet.blockstack.org:16268'
```

I modified the [publicKeyToAddress function in blockstack JS](https://github.com/blockstack/blockstack.js/blob/c9d25ab78cd4f634372e7f0e9d35ebb6c083e7c7/src/keys.js#L17) to use the testnet version 111. 

I opened a related bug noting that we should make sure all address related functions handle different network versions: https://github.com/blockstack/blockstack.js/issues/563


I installed c32check using `npm install c32check` and tried converted the sender address to a stacks address.

```JavaScript
var c32check = require('c32check')
var sk = bsk.makeECPrivateKey()

var sender = bsk.publicKeyToAddress(bsk.getPublicKeyFromPrivate(sk))

var senderStacksAddress = c32check.b58ToC32(sender)

// fund senderStacksAddress from https://testnet.blockstack.org 
```

Entering the resulting address ( the b58check version of which began with an `m`) into the faucet box resulted in a "Failed to convert XXX to a Stacks address" error.

I spent some time digging through the CLI code to try to figure out if I was using an incorrect version or generating the address improperly, but ran out of time.

@jcnelson please let me know what I was doing wrong - either way I think this PR is ready to merge.

2018-11-08 16:58 UTC, kantai commented
> Entering the resulting address ( the b58check version of which began with an m) into the faucet box resulted in a "Failed to convert XXX to a Stacks address" error.

I believe the testnet faucet wants to be provided with a b58 address, not the c32 address. @jcnelson can correct me if I'm wrong there.

> I started going down the rabbit hole of testing this against https://testnet.blockstack.org, but had trouble generating an appropriate stacks address that the faucet would accept.

This PR implements a different kind of testnet -- the "testnet" at testnet.blockstack.org is a blockstack chain running on a regtest bitcoin chain. This PR allows you to submit transactions with a different magic header, which allows you to run a testnet on bitcoin _mainnet_ -- this, in turn, allows you to test things like Stack transfers with "testing Stacks" but with the real Bitcoin chain.

2018-11-08 17:09 UTC, larrysalibra commented
> I believe the testnet faucet wants to be provided with a b58 address, not the c32 address. @jcnelson can correct me if I'm wrong there.

The stacks testnet faucet accepts c32 addresses generated by the `blockstack-cli -t make_keychain` command.

> This PR implements a different kind of testnet -- the "testnet" at testnet.blockstack.org is a blockstack chain running on a regtest bitcoin chain. This PR allows you to submit transactions with a different magic header, which allows you to run a testnet on bitcoin mainnet -- this, in turn, allows you to test things like Stack transfers with "testing Stacks" but with the real Bitcoin chain.

I understand that - the "testnet on regtest" system at testnet.blockstack.org uses `id` as the magic header, so I was trying to set the magic header back to `id` and generate appropriate addresses and then a transaction that would be accepted on that network using this code.

In general, the config.network structure with regards to layer 1 mainnet vs testnet vs regtest and layer 2 mainnet vs testnet is a bit confusing.

We define two constants
LOCAL_REGTEST and MAINNET_DEFAULT that don't make it clear if they're referring to layer 1 or layer 2.

https://github.com/blockstack/blockstack.js/blob/28f44a0531fa315be7b7c00560fc52d7fed84d51/src/network.js#L1190

It seems the names refer to the layer 1 networks, but the settings contained within them also refer to layer 2 components as well.

2018-11-08 17:24 UTC, jcnelson commented
> Entering the resulting address ( the b58check version of which began with an m) into the faucet box resulted in a "Failed to convert XXX to a Stacks address" error.

I'm getting this too.  Will fix.

But nevertheless, you won't be able to test this code on testnet.blockstack.org since testnet.blockstack.org uses the `id` magic.  Its Core node won't pick up any transactions with other magic bytes.

> In general, the config.network structure with regards to layer 1 mainnet vs testnet vs regtest and layer 2 mainnet vs testnet is a bit confusing.

> We define two constants LOCAL_REGTEST and MAINNET_DEFAULT that don't make it clear if they're referring to layer 1 or layer 2.

They both refer to layer 1.  Changes to MAGIC_BYTES affect layer 2.  There are now four classes of network configurations -- `id` on BItcoin mainnet, non-`id` on Bitcoin mainnet, `id` on Bitcoin testnet/regtest, and non-`id` on Bitcoin testnet/regtest.

2018-11-08 17:43 UTC, larrysalibra commented
> But nevertheless, you won't be able to test this code on testnet.blockstack.org since testnet.blockstack.org uses the id magic. Its Core node won't pick up any transactions with other magic bytes.

I tried to set the magic bytes code to the default - `id`- shouldn't that work?

```
bsk.config.network.MAGIC_BYTES = 'id'
// this URL might be different for you...
bsk.config.network.blockstackAPIUrl = 'http://testnet.blockstack.org:16268'
```

2018-11-08 17:48 UTC, jcnelson commented
Yes, that should work.

2018-11-12 22:27 UTC, jcnelson commented
Going to go ahead and merge.  Thanks folks!

2018-11-12 22:27 UTC, merged