Fixes usage of association token with UserSession
stx-labs/stacks.js pull request #645
Opened 2019-04-04 20:30 UTC by hstove

When testing [Jude's association token PR](https://github.com/blockstack/blockstack-browser/pull/1833/files), I found a bug when using association tokens with v19. The issue is that, when calling `handlePendingSignIn`, we pass the `associationToken` property of the `authResponse` to the `gaiaAssociationToken` property of `userData`. However, when calling `setLocalGaiaHubConnection`, we were using the `associationToken` property of `userData`. This is always null, so the association token is not used.

I would also suggest that we remove the `associationToken` property from `userData`.

2019-04-05 21:57 UTC, zone117x commented
Nice find @hstove. I've been confused about those two fields. 

> I would also suggest that we remove the associationToken property from userData.

Could you do this in this PR?

2019-04-05 21:58 UTC, zone117x requested changes
Nice find @hstove. I've been confused about those two fields. 

> I would also suggest that we remove the associationToken property from userData.

Could you do this in this PR?

2019-04-08 16:19 UTC, yknl approved these changes
Thanks for the fix!

2019-04-08 16:48 UTC, jcnelson commented
Looks good to me.  Thanks for taking the time @hstove!

2019-04-08 16:48 UTC, jcnelson approved these changes

2019-04-08 16:51 UTC, hstove commented
@zone117x good call, done :+1:

2019-04-08 17:11 UTC, zone117x approved these changes

2019-04-09 16:33 UTC, merged