Add types for auth scopes
stx-labs/stacks.js pull request #651
Opened 2019-04-18 22:15 UTC by zone117x

2019-04-23 22:47 UTC, moxiegirl commented on src/auth/authConstants.ts
> +   * The user's files stored on Gaia are made visible to others via the apps property in the
Never Gaia alone -- Gaia hub

2019-04-23 22:48 UTC, moxiegirl requested changes
Couple little nits to fix

2019-05-10 15:50 UTC, yknl approved these changes
Looks good to me!

2019-05-10 17:31 UTC, zone117x commented on src/auth/authConstants.ts
> +   * The user's files stored on Gaia are made visible to others via the apps property in the
Fixed

2019-05-15 00:20 UTC, moxiegirl approved these changes

2019-05-15 00:23 UTC, merged