Throw error on user session overwrite
stx-labs/stacks.js pull request #682
Opened 2019-07-23 19:35 UTC by yknl

`handlePendingSignIn` now throws an error when a user session already exists in local storage. Addresses https://github.com/blockstack/blockstack.js/issues/680

Testing:
1. Use any Blockstack app and link with this branch
2. Sign in to app 
3. Go back to sign in page on app and click sign in again, choose identity to use
4. App should error out

2019-07-24 06:02 UTC, friedger commented
The documentation should suggest how to handle this exception.

2019-07-24 13:41 UTC, hstove requested changes
Tiny change requested, otherwise LGTM!

2019-07-24 13:41 UTC, hstove commented on tests/unitTests/src/unitTestsAuth.ts
> +        console.log(err.stack)
Let's remove this, especially since this is the 'expected' code path

2019-07-30 13:01 UTC, zone117x approved these changes
This probably fixes most of these cases and we should merge, but I think there are more situations that would cause similar issues described in https://github.com/blockstack/blockstack.js/issues/680

Several tabs could be open and logged in for an app. User could logout (clear localStorage) on tab 1, then login with different account, and still remained logged in with original account in tab 2, potentially causing issues depending on how the app is designed. This could be addressed in another PR.

2019-08-07 21:00 UTC, merged