[DOC] Clarify file count for listFile
stx-labs/stacks.js pull request #734
Opened 2019-10-03 07:47 UTC by friedger

## Description
This PR extends the result description of `listFiles` for the case the the listing was ended through the callback (returned false)

## Type of Change
- [ ] New feature
- [ ] Bug fix
- [x] API reference/documentation update
- [ ] Other

## Does this introduce a breaking change?
no
## Are documentation updates required?

## Checklist
- [x] Code is commented where needed
- [x] Unit test coverage for new or modified code paths
- [x] `npm run test` passes
- [x] Changelog is updated
- [x] Tag 1 of @yknl or @zone117x for review

2019-10-04 16:52 UTC, moxiegirl requested changes
This read a bit awkwardly. See suggested changs.

2019-10-04 16:52 UTC, moxiegirl commented on src/storage/index.ts
> + * @return {Promise} that resolves to the number of files listed (excluding the last if ended early), or rejects with an error.
> that resolves to the number of files listed (excluding the last if ended early), or rejects with an error.

Resolves to the total number of listed files.  If the call is ended early, the last file is excluded or the entire call rejects with an error.

2019-10-17 19:06 UTC, yknl commented
@friedger can you take a look?

2019-10-17 19:40 UTC, friedger commented
@moxiegirl I have adopted your suggestion

2019-10-30 12:26 UTC, friedger commented
Is this good to merge?

2019-10-30 17:02 UTC, moxiegirl approved these changes

2019-11-05 19:23 UTC, zone117x approved these changes

2019-11-05 19:23 UTC, merged